---
apiVersion: v1
automountServiceAccountToken: true
imagePullSecrets:
  - name: <source>
kind: ServiceAccount
metadata:
  name: service-scaler-operator
  namespace: <ns>
  labels:
    app.kubernetes.io/name: service-scaler-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-scaler-operator
  labels:
    app.kubernetes.io/name: service-scaler-operator
rules:
  - apiGroups:
      - ''
      - 'autoscaling'
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - get
      - list
      - patch
      - delete
  - apiGroups:
      - ''
      - 'scaler.udaan.io'
    resources:
      - servicescalers
      - servicescalers/status
    verbs:
      - get
      - list
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-scaler-operator
  labels:
    app.kubernetes.io/name: service-scaler-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-scaler-operator
subjects:
  - kind: ServiceAccount
    name: service-scaler-operator
    namespace: <ns>