apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicescalers.scaler.udaan.io
spec:
  group: scaler.udaan.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hpa:
                  description: 'default hpa configuration.'
                  type: object
                  properties:
                    minReplicas:
                      type: integer
                    maxReplicas:
                      type: integer
                    targetCPUUtilization:
                      type: integer
                    targetMemoryUtilization:
                      type: integer
                  required:
                    - minReplicas
                    - maxReplicas
                timeRangeSpec:
                  type: array
                  description: 'describes time ranges to be matched and the corresponding overrides to be applied.'
                  items:
                    type: object
                    properties:
                      kind:
                        type: string
                      from:
                        type: string
                      to:
                        type: string
                      replicaSpec:
                        type: object
                        properties:
                          hpa:
                            type: object
                            properties:
                              minReplicas:
                                type: integer
                              maxReplicas:
                                type: integer
                              targetCPUUtilization:
                                type: integer
                              targetMemoryUtilization:
                                type: integer
                            required: []
            status:
              type: object
              properties:
                timeRangeMatch:
                  type: boolean
                lastAction:
                  type: string
                lastObservedGeneration:
                  type: integer
                lastKnownConfig:
                  type: object
                  properties:
                    maxReplicas:
                      type: integer
                    minReplicas:
                      type: integer
                    targetCPUUtilization:
                      type: integer
                    targetMemoryUtilization:
                      type: integer
                  required: []
                lastUpdatedTime:
                  type: string
              required: []
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: servicescalers
    singular: servicescaler
    kind: ServiceScaler
    shortNames:
      - ss